export enum PlannerModels {
    // GPT_5 = "openai:gpt-5",
    GPT_5_5 = "openai:gpt-5.5",
    GPT_5_4 = "openai:gpt-5.4",
    GPT_5_4_MINI = "openai:gpt-5.4-mini",
    GPT_5_2 = "openai:gpt-5.2",
    GPT_5_1 = "openai:gpt-5.1",
    GPT_5 = "openai:gpt-5",
    GEMINI_3 = "google_genai:gemini-3-pro-preview",
    GEMINI_3_FLASH = "google_genai:gemini-3-flash-preview",
    SONNET_4_6 = "anthropic:claude-sonnet-4-6",
    SONNET_4_5 = "anthropic:claude-sonnet-4-5-20250929",
    HAIKU_4_5 = "anthropic:claude-haiku-4-5-20251001",
    DEEPSEEK_V4_PRO = "deepseek:deepseek-v4-pro",
    DEEPSEEK_V4_PRO_NVIDIA = "nvidia:deepseek-ai/deepseek-v4-pro",
}